# Configure the database used when in the development environment
development:
  adapter: postgresql
  encoding: unicode
  database: <app-name>_development
  pool: 5
  username:
  password:

# Configure the database used when in the test environment
test:
  adapter: postgresql
  encoding: unicode
  database: <app-name>_test
  pool: 5
  username:
  password:
